name: workflow
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
        sudo luarocks install luacheck
    - uses: pre-commit/action@v2.0.3
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - run: docker-compose build
  release:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
    - uses: google-github-actions/setup-gcloud@v0
    - run: gcloud auth configure-docker us-central1-docker.pkg.dev
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - run: docker-compose build
    - run: docker tag wowless-dev/wowless:base us-central1-docker.pkg.dev/www-wowless-dev/docker/wowless:latest
    - run: docker push us-central1-docker.pkg.dev/www-wowless-dev/docker/wowless:latest
    - uses: google-github-actions/deploy-cloudrun@v0
      with:
        image: us-central1-docker.pkg.dev/www-wowless-dev/docker/wowless
        service: wowless
